/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface StatResult {
  dev: number
  ino: number
  mode: number
  nlink: number
  uid: number
  gid: number
  rdev: number
  size: number
  blksize: number
  blocks: number
  atimeNs: number
  mtimeNs: number
  ctimeNs: number
}
export declare class SandboxRoot {
  constructor(root: string)
  mkdir(path: string, recursive?: boolean | undefined | null, mode?: number | undefined | null): void
  unlink(path: string): void
  rmdir(path: string): void
  rename(oldPath: string, newPath: string): void
  renameNoReplace(oldPath: string, newPath: string): void
  link(oldPath: string, newPath: string): void
  chmod(path: string, mode: number): void
  truncate(path: string, len: number): void
  copyFile(src: string, dest: string, mode?: number | undefined | null): void
  rm(path: string, recursive?: boolean | undefined | null, force?: boolean | undefined | null): void
  utimes(path: string, atimeNs: number, mtimeNs: number): void
  stat(path: string): StatResult
}
